# Generated by Django 2.1.8 on 2019-06-12 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190612_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content5',
        ),
    ]
